apiVersion: v1
kind: ConfigMap
metadata:
  name: nexa-bank-config
  namespace: nexa-bank
data:
  POSTGRES_USER: nexa
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  CUSTOMER_DATABASE_URL: jdbc:postgresql://postgres:5432/nexa_customer
  ACCOUNT_DATABASE_URL: jdbc:postgresql://postgres:5432/nexa_account
  TRANSACTION_DATABASE_URL: jdbc:postgresql://postgres:5432/nexa_transaction
  AUDIT_DATABASE_URL: jdbc:postgresql://postgres:5432/nexa_audit
  RAG_DB_URL: jdbc:postgresql://postgres:5432/nexa_rag
  CUSTOMER_SERVICE_URL: http://customer-service:8081
  ACCOUNT_SERVICE_URL: http://account-service:8082
  TRANSACTION_SERVICE_URL: http://transaction-service:8083
  AGENT_SERVICE_URL: http://agent-service:8091
  BANKING_GATEWAY_URL: http://api-gateway:8080
  BANKING_MCP_URL: http://banking-mcp-server:8090
  OLLAMA_BASE_URL: http://ollama:11434
  RAG_INGEST_ON_STARTUP: "false"

